# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .search_get_request_clustering_variable import SearchGetRequestClusteringVariable
    from .search_get_request_news_domain_type import SearchGetRequestNewsDomainType
    from .search_get_request_published_date_precision import SearchGetRequestPublishedDatePrecision
    from .search_get_request_sort_by import SearchGetRequestSortBy
    from .search_get_response import SearchGetResponse
    from .search_post_response import SearchPostResponse
_dynamic_imports: typing.Dict[str, str] = {
    "SearchGetRequestClusteringVariable": ".search_get_request_clustering_variable",
    "SearchGetRequestNewsDomainType": ".search_get_request_news_domain_type",
    "SearchGetRequestPublishedDatePrecision": ".search_get_request_published_date_precision",
    "SearchGetRequestSortBy": ".search_get_request_sort_by",
    "SearchGetResponse": ".search_get_response",
    "SearchPostResponse": ".search_post_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SearchGetRequestClusteringVariable",
    "SearchGetRequestNewsDomainType",
    "SearchGetRequestPublishedDatePrecision",
    "SearchGetRequestSortBy",
    "SearchGetResponse",
    "SearchPostResponse",
]
