# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.breaking_news_response_dto import BreakingNewsResponseDto
from ..types.content_sentiment_max import ContentSentimentMax
from ..types.content_sentiment_min import ContentSentimentMin
from ..types.from_rank import FromRank
from ..types.has_nlp import HasNlp
from ..types.include_nlp_data import IncludeNlpData
from ..types.include_translation_fields import IncludeTranslationFields
from ..types.loc_entity_name import LocEntityName
from ..types.misc_entity_name import MiscEntityName
from ..types.not_theme import NotTheme
from ..types.org_entity_name import OrgEntityName
from ..types.page import Page
from ..types.page_size import PageSize
from ..types.per_entity_name import PerEntityName
from ..types.ranked_only import RankedOnly
from ..types.sort_by import SortBy
from ..types.theme import Theme
from ..types.title_sentiment_max import TitleSentimentMax
from ..types.title_sentiment_min import TitleSentimentMin
from ..types.to_rank import ToRank
from ..types.top_n_articles import TopNArticles
from .raw_client import AsyncRawBreakingNewsClient, RawBreakingNewsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BreakingNewsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBreakingNewsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBreakingNewsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBreakingNewsClient
        """
        return self._raw_client

    def breaking_news_get(
        self,
        *,
        sort_by: typing.Optional[SortBy] = None,
        ranked_only: typing.Optional[RankedOnly] = None,
        from_rank: typing.Optional[FromRank] = None,
        to_rank: typing.Optional[ToRank] = None,
        page: typing.Optional[Page] = None,
        page_size: typing.Optional[PageSize] = None,
        top_n_articles: typing.Optional[TopNArticles] = None,
        include_translation_fields: typing.Optional[IncludeTranslationFields] = None,
        include_nlp_data: typing.Optional[IncludeNlpData] = None,
        has_nlp: typing.Optional[HasNlp] = None,
        theme: typing.Optional[Theme] = None,
        not_theme: typing.Optional[NotTheme] = None,
        org_entity_name: typing.Optional[OrgEntityName] = None,
        per_entity_name: typing.Optional[PerEntityName] = None,
        loc_entity_name: typing.Optional[LocEntityName] = None,
        misc_entity_name: typing.Optional[MiscEntityName] = None,
        title_sentiment_min: typing.Optional[TitleSentimentMin] = None,
        title_sentiment_max: typing.Optional[TitleSentimentMax] = None,
        content_sentiment_min: typing.Optional[ContentSentimentMin] = None,
        content_sentiment_max: typing.Optional[ContentSentimentMax] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BreakingNewsResponseDto:
        """
        Retrieves breaking news articles and sorts them based on specified criteria.

        Parameters
        ----------
        sort_by : typing.Optional[SortBy]

        ranked_only : typing.Optional[RankedOnly]

        from_rank : typing.Optional[FromRank]

        to_rank : typing.Optional[ToRank]

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        top_n_articles : typing.Optional[TopNArticles]

        include_translation_fields : typing.Optional[IncludeTranslationFields]

        include_nlp_data : typing.Optional[IncludeNlpData]

        has_nlp : typing.Optional[HasNlp]

        theme : typing.Optional[Theme]

        not_theme : typing.Optional[NotTheme]

        org_entity_name : typing.Optional[OrgEntityName]

        per_entity_name : typing.Optional[PerEntityName]

        loc_entity_name : typing.Optional[LocEntityName]

        misc_entity_name : typing.Optional[MiscEntityName]

        title_sentiment_min : typing.Optional[TitleSentimentMin]

        title_sentiment_max : typing.Optional[TitleSentimentMax]

        content_sentiment_min : typing.Optional[ContentSentimentMin]

        content_sentiment_max : typing.Optional[ContentSentimentMax]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BreakingNewsResponseDto
            A successful response containing breaking news articles with additional breaking news event information.

        Examples
        --------
        from newscatcher import NewscatcherApi

        client = NewscatcherApi(
            api_key="YOUR_API_KEY",
        )
        client.breaking_news.breaking_news_get(
            ranked_only=True,
            from_rank=100,
            to_rank=100,
            page=2,
            page_size=50,
            top_n_articles=5,
            include_translation_fields=True,
            include_nlp_data=True,
            has_nlp=True,
            theme="Finance,Tech",
            not_theme="Crime,Sports",
            org_entity_name='"Apple Inc" OR Microsoft',
            per_entity_name='"Elon Musk" OR "Jeff Bezos"',
            loc_entity_name='"San Francisco" OR "New York City"',
            misc_entity_name='AWS OR "Microsoft Azure"',
            title_sentiment_min=-0.5,
            title_sentiment_max=0.5,
            content_sentiment_min=-0.5,
            content_sentiment_max=0.5,
        )
        """
        _response = self._raw_client.breaking_news_get(
            sort_by=sort_by,
            ranked_only=ranked_only,
            from_rank=from_rank,
            to_rank=to_rank,
            page=page,
            page_size=page_size,
            top_n_articles=top_n_articles,
            include_translation_fields=include_translation_fields,
            include_nlp_data=include_nlp_data,
            has_nlp=has_nlp,
            theme=theme,
            not_theme=not_theme,
            org_entity_name=org_entity_name,
            per_entity_name=per_entity_name,
            loc_entity_name=loc_entity_name,
            misc_entity_name=misc_entity_name,
            title_sentiment_min=title_sentiment_min,
            title_sentiment_max=title_sentiment_max,
            content_sentiment_min=content_sentiment_min,
            content_sentiment_max=content_sentiment_max,
            request_options=request_options,
        )
        return _response.data

    def breaking_news_post(
        self,
        *,
        sort_by: typing.Optional[SortBy] = OMIT,
        ranked_only: typing.Optional[RankedOnly] = OMIT,
        from_rank: typing.Optional[FromRank] = OMIT,
        to_rank: typing.Optional[ToRank] = OMIT,
        page: typing.Optional[Page] = OMIT,
        page_size: typing.Optional[PageSize] = OMIT,
        top_n_articles: typing.Optional[TopNArticles] = OMIT,
        include_translation_fields: typing.Optional[IncludeTranslationFields] = OMIT,
        include_nlp_data: typing.Optional[IncludeNlpData] = OMIT,
        has_nlp: typing.Optional[HasNlp] = OMIT,
        theme: typing.Optional[Theme] = OMIT,
        not_theme: typing.Optional[NotTheme] = OMIT,
        org_entity_name: typing.Optional[OrgEntityName] = OMIT,
        per_entity_name: typing.Optional[PerEntityName] = OMIT,
        loc_entity_name: typing.Optional[LocEntityName] = OMIT,
        misc_entity_name: typing.Optional[MiscEntityName] = OMIT,
        title_sentiment_min: typing.Optional[TitleSentimentMin] = OMIT,
        title_sentiment_max: typing.Optional[TitleSentimentMax] = OMIT,
        content_sentiment_min: typing.Optional[ContentSentimentMin] = OMIT,
        content_sentiment_max: typing.Optional[ContentSentimentMax] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BreakingNewsResponseDto:
        """
        Retrieves breaking news articles and sorts them based on specified criteria.

        Parameters
        ----------
        sort_by : typing.Optional[SortBy]

        ranked_only : typing.Optional[RankedOnly]

        from_rank : typing.Optional[FromRank]

        to_rank : typing.Optional[ToRank]

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        top_n_articles : typing.Optional[TopNArticles]

        include_translation_fields : typing.Optional[IncludeTranslationFields]

        include_nlp_data : typing.Optional[IncludeNlpData]

        has_nlp : typing.Optional[HasNlp]

        theme : typing.Optional[Theme]

        not_theme : typing.Optional[NotTheme]

        org_entity_name : typing.Optional[OrgEntityName]

        per_entity_name : typing.Optional[PerEntityName]

        loc_entity_name : typing.Optional[LocEntityName]

        misc_entity_name : typing.Optional[MiscEntityName]

        title_sentiment_min : typing.Optional[TitleSentimentMin]

        title_sentiment_max : typing.Optional[TitleSentimentMax]

        content_sentiment_min : typing.Optional[ContentSentimentMin]

        content_sentiment_max : typing.Optional[ContentSentimentMax]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BreakingNewsResponseDto
            A successful response containing breaking news articles with additional breaking news event information.

        Examples
        --------
        from newscatcher import NewscatcherApi

        client = NewscatcherApi(
            api_key="YOUR_API_KEY",
        )
        client.breaking_news.breaking_news_post(
            sort_by="relevancy",
            ranked_only=True,
            top_n_articles=1,
        )
        """
        _response = self._raw_client.breaking_news_post(
            sort_by=sort_by,
            ranked_only=ranked_only,
            from_rank=from_rank,
            to_rank=to_rank,
            page=page,
            page_size=page_size,
            top_n_articles=top_n_articles,
            include_translation_fields=include_translation_fields,
            include_nlp_data=include_nlp_data,
            has_nlp=has_nlp,
            theme=theme,
            not_theme=not_theme,
            org_entity_name=org_entity_name,
            per_entity_name=per_entity_name,
            loc_entity_name=loc_entity_name,
            misc_entity_name=misc_entity_name,
            title_sentiment_min=title_sentiment_min,
            title_sentiment_max=title_sentiment_max,
            content_sentiment_min=content_sentiment_min,
            content_sentiment_max=content_sentiment_max,
            request_options=request_options,
        )
        return _response.data


class AsyncBreakingNewsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBreakingNewsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBreakingNewsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBreakingNewsClient
        """
        return self._raw_client

    async def breaking_news_get(
        self,
        *,
        sort_by: typing.Optional[SortBy] = None,
        ranked_only: typing.Optional[RankedOnly] = None,
        from_rank: typing.Optional[FromRank] = None,
        to_rank: typing.Optional[ToRank] = None,
        page: typing.Optional[Page] = None,
        page_size: typing.Optional[PageSize] = None,
        top_n_articles: typing.Optional[TopNArticles] = None,
        include_translation_fields: typing.Optional[IncludeTranslationFields] = None,
        include_nlp_data: typing.Optional[IncludeNlpData] = None,
        has_nlp: typing.Optional[HasNlp] = None,
        theme: typing.Optional[Theme] = None,
        not_theme: typing.Optional[NotTheme] = None,
        org_entity_name: typing.Optional[OrgEntityName] = None,
        per_entity_name: typing.Optional[PerEntityName] = None,
        loc_entity_name: typing.Optional[LocEntityName] = None,
        misc_entity_name: typing.Optional[MiscEntityName] = None,
        title_sentiment_min: typing.Optional[TitleSentimentMin] = None,
        title_sentiment_max: typing.Optional[TitleSentimentMax] = None,
        content_sentiment_min: typing.Optional[ContentSentimentMin] = None,
        content_sentiment_max: typing.Optional[ContentSentimentMax] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BreakingNewsResponseDto:
        """
        Retrieves breaking news articles and sorts them based on specified criteria.

        Parameters
        ----------
        sort_by : typing.Optional[SortBy]

        ranked_only : typing.Optional[RankedOnly]

        from_rank : typing.Optional[FromRank]

        to_rank : typing.Optional[ToRank]

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        top_n_articles : typing.Optional[TopNArticles]

        include_translation_fields : typing.Optional[IncludeTranslationFields]

        include_nlp_data : typing.Optional[IncludeNlpData]

        has_nlp : typing.Optional[HasNlp]

        theme : typing.Optional[Theme]

        not_theme : typing.Optional[NotTheme]

        org_entity_name : typing.Optional[OrgEntityName]

        per_entity_name : typing.Optional[PerEntityName]

        loc_entity_name : typing.Optional[LocEntityName]

        misc_entity_name : typing.Optional[MiscEntityName]

        title_sentiment_min : typing.Optional[TitleSentimentMin]

        title_sentiment_max : typing.Optional[TitleSentimentMax]

        content_sentiment_min : typing.Optional[ContentSentimentMin]

        content_sentiment_max : typing.Optional[ContentSentimentMax]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BreakingNewsResponseDto
            A successful response containing breaking news articles with additional breaking news event information.

        Examples
        --------
        import asyncio

        from newscatcher import AsyncNewscatcherApi

        client = AsyncNewscatcherApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.breaking_news.breaking_news_get(
                ranked_only=True,
                from_rank=100,
                to_rank=100,
                page=2,
                page_size=50,
                top_n_articles=5,
                include_translation_fields=True,
                include_nlp_data=True,
                has_nlp=True,
                theme="Finance,Tech",
                not_theme="Crime,Sports",
                org_entity_name='"Apple Inc" OR Microsoft',
                per_entity_name='"Elon Musk" OR "Jeff Bezos"',
                loc_entity_name='"San Francisco" OR "New York City"',
                misc_entity_name='AWS OR "Microsoft Azure"',
                title_sentiment_min=-0.5,
                title_sentiment_max=0.5,
                content_sentiment_min=-0.5,
                content_sentiment_max=0.5,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.breaking_news_get(
            sort_by=sort_by,
            ranked_only=ranked_only,
            from_rank=from_rank,
            to_rank=to_rank,
            page=page,
            page_size=page_size,
            top_n_articles=top_n_articles,
            include_translation_fields=include_translation_fields,
            include_nlp_data=include_nlp_data,
            has_nlp=has_nlp,
            theme=theme,
            not_theme=not_theme,
            org_entity_name=org_entity_name,
            per_entity_name=per_entity_name,
            loc_entity_name=loc_entity_name,
            misc_entity_name=misc_entity_name,
            title_sentiment_min=title_sentiment_min,
            title_sentiment_max=title_sentiment_max,
            content_sentiment_min=content_sentiment_min,
            content_sentiment_max=content_sentiment_max,
            request_options=request_options,
        )
        return _response.data

    async def breaking_news_post(
        self,
        *,
        sort_by: typing.Optional[SortBy] = OMIT,
        ranked_only: typing.Optional[RankedOnly] = OMIT,
        from_rank: typing.Optional[FromRank] = OMIT,
        to_rank: typing.Optional[ToRank] = OMIT,
        page: typing.Optional[Page] = OMIT,
        page_size: typing.Optional[PageSize] = OMIT,
        top_n_articles: typing.Optional[TopNArticles] = OMIT,
        include_translation_fields: typing.Optional[IncludeTranslationFields] = OMIT,
        include_nlp_data: typing.Optional[IncludeNlpData] = OMIT,
        has_nlp: typing.Optional[HasNlp] = OMIT,
        theme: typing.Optional[Theme] = OMIT,
        not_theme: typing.Optional[NotTheme] = OMIT,
        org_entity_name: typing.Optional[OrgEntityName] = OMIT,
        per_entity_name: typing.Optional[PerEntityName] = OMIT,
        loc_entity_name: typing.Optional[LocEntityName] = OMIT,
        misc_entity_name: typing.Optional[MiscEntityName] = OMIT,
        title_sentiment_min: typing.Optional[TitleSentimentMin] = OMIT,
        title_sentiment_max: typing.Optional[TitleSentimentMax] = OMIT,
        content_sentiment_min: typing.Optional[ContentSentimentMin] = OMIT,
        content_sentiment_max: typing.Optional[ContentSentimentMax] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BreakingNewsResponseDto:
        """
        Retrieves breaking news articles and sorts them based on specified criteria.

        Parameters
        ----------
        sort_by : typing.Optional[SortBy]

        ranked_only : typing.Optional[RankedOnly]

        from_rank : typing.Optional[FromRank]

        to_rank : typing.Optional[ToRank]

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        top_n_articles : typing.Optional[TopNArticles]

        include_translation_fields : typing.Optional[IncludeTranslationFields]

        include_nlp_data : typing.Optional[IncludeNlpData]

        has_nlp : typing.Optional[HasNlp]

        theme : typing.Optional[Theme]

        not_theme : typing.Optional[NotTheme]

        org_entity_name : typing.Optional[OrgEntityName]

        per_entity_name : typing.Optional[PerEntityName]

        loc_entity_name : typing.Optional[LocEntityName]

        misc_entity_name : typing.Optional[MiscEntityName]

        title_sentiment_min : typing.Optional[TitleSentimentMin]

        title_sentiment_max : typing.Optional[TitleSentimentMax]

        content_sentiment_min : typing.Optional[ContentSentimentMin]

        content_sentiment_max : typing.Optional[ContentSentimentMax]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BreakingNewsResponseDto
            A successful response containing breaking news articles with additional breaking news event information.

        Examples
        --------
        import asyncio

        from newscatcher import AsyncNewscatcherApi

        client = AsyncNewscatcherApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.breaking_news.breaking_news_post(
                sort_by="relevancy",
                ranked_only=True,
                top_n_articles=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.breaking_news_post(
            sort_by=sort_by,
            ranked_only=ranked_only,
            from_rank=from_rank,
            to_rank=to_rank,
            page=page,
            page_size=page_size,
            top_n_articles=top_n_articles,
            include_translation_fields=include_translation_fields,
            include_nlp_data=include_nlp_data,
            has_nlp=has_nlp,
            theme=theme,
            not_theme=not_theme,
            org_entity_name=org_entity_name,
            per_entity_name=per_entity_name,
            loc_entity_name=loc_entity_name,
            misc_entity_name=misc_entity_name,
            title_sentiment_min=title_sentiment_min,
            title_sentiment_max=title_sentiment_max,
            content_sentiment_min=content_sentiment_min,
            content_sentiment_max=content_sentiment_max,
            request_options=request_options,
        )
        return _response.data
