# This file was auto-generated by Fern from our API Definition.

import typing

from .aggregation_item import AggregationItem

AggregationCountResponseDtoAggregations = typing.Union[AggregationItem, typing.List[AggregationItem]]
