# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AllLinksDataItem(UniversalBaseModel):
    """
    Detailed information about a link found in an article.
    """

    domain_url: str = pydantic.Field()
    """
    The domain of the linked URL.
    """

    link: str = pydantic.Field()
    """
    The complete URL of the link.
    """

    text: str = pydantic.Field()
    """
    The anchor text of the link.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
