# This file was auto-generated by Fern from our API Definition.

import typing

from .article_entity import ArticleEntity

ArticlesDto = typing.List[ArticleEntity]
"""
A list of articles matching the search criteria.
"""
