# This file was auto-generated by Fern from our API Definition.

ExcludeDuplicates = bool
"""
If true, excludes duplicate and highly similar articles from the search results. If false, returns all relevant articles, including duplicates. 

To learn more, see [Articles deduplication](https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/articles-deduplication).
"""
