# This file was auto-generated by Fern from our API Definition.

IncludeTranslationFields = bool
"""
If true, includes English translation fields in the response (`title_translated_en`, `content_translated_en`, and NLP translation fields).
"""
