# This file was auto-generated by Fern from our API Definition.

Page = int
"""
The page number to scroll through the results. Use for pagination, as a single API response can return up to 1,000 articles. 

For details, see [How to paginate large datasets](https://www.newscatcherapi.com/docs/news-api/how-to/paginate-large-datasets).
"""
