# This file was auto-generated by Fern from our API Definition.

RankedOnly = bool
"""
If true, limits the search to sources ranked in the top 1 million online websites. If false, includes unranked sources which are assigned a rank of 999999.
"""
