# This file was auto-generated by Fern from our API Definition.

RobotsCompliant = bool
"""
If true, returns only articles that comply with the publisher's robots.txt rules. If false, returns only articles that do not comply with robots.txt rules. If omitted, returns all articles regardless of compliance status.
"""
