# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import NewscatcherApiEnvironment

if typing.TYPE_CHECKING:
    from .aggregation.client import AggregationClient, AsyncAggregationClient
    from .authors.client import AsyncAuthorsClient, AuthorsClient
    from .breaking_news.client import AsyncBreakingNewsClient, BreakingNewsClient
    from .latest_headlines.client import AsyncLatestHeadlinesClient, LatestHeadlinesClient
    from .search.client import AsyncSearchClient, SearchClient
    from .search_by_link.client import AsyncSearchByLinkClient, SearchByLinkClient
    from .sources.client import AsyncSourcesClient, SourcesClient
    from .subscription.client import AsyncSubscriptionClient, SubscriptionClient


class BaseNewscatcherApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : NewscatcherApiEnvironment
        The environment to use for requests from the client. from .environment import NewscatcherApiEnvironment



        Defaults to NewscatcherApiEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from newscatcher import NewscatcherApi

    client = NewscatcherApi(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: NewscatcherApiEnvironment = NewscatcherApiEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._search: typing.Optional[SearchClient] = None
        self._latest_headlines: typing.Optional[LatestHeadlinesClient] = None
        self._breaking_news: typing.Optional[BreakingNewsClient] = None
        self._authors: typing.Optional[AuthorsClient] = None
        self._search_by_link: typing.Optional[SearchByLinkClient] = None
        self._sources: typing.Optional[SourcesClient] = None
        self._aggregation: typing.Optional[AggregationClient] = None
        self._subscription: typing.Optional[SubscriptionClient] = None

    @property
    def search(self):
        if self._search is None:
            from .search.client import SearchClient  # noqa: E402

            self._search = SearchClient(client_wrapper=self._client_wrapper)
        return self._search

    @property
    def latest_headlines(self):
        if self._latest_headlines is None:
            from .latest_headlines.client import LatestHeadlinesClient  # noqa: E402

            self._latest_headlines = LatestHeadlinesClient(client_wrapper=self._client_wrapper)
        return self._latest_headlines

    @property
    def breaking_news(self):
        if self._breaking_news is None:
            from .breaking_news.client import BreakingNewsClient  # noqa: E402

            self._breaking_news = BreakingNewsClient(client_wrapper=self._client_wrapper)
        return self._breaking_news

    @property
    def authors(self):
        if self._authors is None:
            from .authors.client import AuthorsClient  # noqa: E402

            self._authors = AuthorsClient(client_wrapper=self._client_wrapper)
        return self._authors

    @property
    def search_by_link(self):
        if self._search_by_link is None:
            from .search_by_link.client import SearchByLinkClient  # noqa: E402

            self._search_by_link = SearchByLinkClient(client_wrapper=self._client_wrapper)
        return self._search_by_link

    @property
    def sources(self):
        if self._sources is None:
            from .sources.client import SourcesClient  # noqa: E402

            self._sources = SourcesClient(client_wrapper=self._client_wrapper)
        return self._sources

    @property
    def aggregation(self):
        if self._aggregation is None:
            from .aggregation.client import AggregationClient  # noqa: E402

            self._aggregation = AggregationClient(client_wrapper=self._client_wrapper)
        return self._aggregation

    @property
    def subscription(self):
        if self._subscription is None:
            from .subscription.client import SubscriptionClient  # noqa: E402

            self._subscription = SubscriptionClient(client_wrapper=self._client_wrapper)
        return self._subscription


class AsyncBaseNewscatcherApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : NewscatcherApiEnvironment
        The environment to use for requests from the client. from .environment import NewscatcherApiEnvironment



        Defaults to NewscatcherApiEnvironment.DEFAULT



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from newscatcher import AsyncNewscatcherApi

    client = AsyncNewscatcherApi(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: NewscatcherApiEnvironment = NewscatcherApiEnvironment.DEFAULT,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._search: typing.Optional[AsyncSearchClient] = None
        self._latest_headlines: typing.Optional[AsyncLatestHeadlinesClient] = None
        self._breaking_news: typing.Optional[AsyncBreakingNewsClient] = None
        self._authors: typing.Optional[AsyncAuthorsClient] = None
        self._search_by_link: typing.Optional[AsyncSearchByLinkClient] = None
        self._sources: typing.Optional[AsyncSourcesClient] = None
        self._aggregation: typing.Optional[AsyncAggregationClient] = None
        self._subscription: typing.Optional[AsyncSubscriptionClient] = None

    @property
    def search(self):
        if self._search is None:
            from .search.client import AsyncSearchClient  # noqa: E402

            self._search = AsyncSearchClient(client_wrapper=self._client_wrapper)
        return self._search

    @property
    def latest_headlines(self):
        if self._latest_headlines is None:
            from .latest_headlines.client import AsyncLatestHeadlinesClient  # noqa: E402

            self._latest_headlines = AsyncLatestHeadlinesClient(client_wrapper=self._client_wrapper)
        return self._latest_headlines

    @property
    def breaking_news(self):
        if self._breaking_news is None:
            from .breaking_news.client import AsyncBreakingNewsClient  # noqa: E402

            self._breaking_news = AsyncBreakingNewsClient(client_wrapper=self._client_wrapper)
        return self._breaking_news

    @property
    def authors(self):
        if self._authors is None:
            from .authors.client import AsyncAuthorsClient  # noqa: E402

            self._authors = AsyncAuthorsClient(client_wrapper=self._client_wrapper)
        return self._authors

    @property
    def search_by_link(self):
        if self._search_by_link is None:
            from .search_by_link.client import AsyncSearchByLinkClient  # noqa: E402

            self._search_by_link = AsyncSearchByLinkClient(client_wrapper=self._client_wrapper)
        return self._search_by_link

    @property
    def sources(self):
        if self._sources is None:
            from .sources.client import AsyncSourcesClient  # noqa: E402

            self._sources = AsyncSourcesClient(client_wrapper=self._client_wrapper)
        return self._sources

    @property
    def aggregation(self):
        if self._aggregation is None:
            from .aggregation.client import AsyncAggregationClient  # noqa: E402

            self._aggregation = AsyncAggregationClient(client_wrapper=self._client_wrapper)
        return self._aggregation

    @property
    def subscription(self):
        if self._subscription is None:
            from .subscription.client import AsyncSubscriptionClient  # noqa: E402

            self._subscription = AsyncSubscriptionClient(client_wrapper=self._client_wrapper)
        return self._subscription


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: NewscatcherApiEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
