# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.from_ import From
from ..types.ids import Ids
from ..types.links import Links
from ..types.page import Page
from ..types.page_size import PageSize
from ..types.robots_compliant import RobotsCompliant
from ..types.search_response_dto import SearchResponseDto
from ..types.to import To
from .raw_client import AsyncRawSearchByLinkClient, RawSearchByLinkClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SearchByLinkClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchByLinkClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchByLinkClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchByLinkClient
        """
        return self._raw_client

    def search_by_link_get(
        self,
        *,
        ids: typing.Optional[str] = None,
        links: typing.Optional[str] = None,
        from_: typing.Optional[From] = None,
        to: typing.Optional[To] = None,
        page: typing.Optional[Page] = None,
        page_size: typing.Optional[PageSize] = None,
        robots_compliant: typing.Optional[RobotsCompliant] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponseDto:
        """
        Searches for articles based on specified links or IDs. You can filter results by date range.

        Parameters
        ----------
        ids : typing.Optional[str]
            The Newscatcher article ID (corresponds to the `_id` field in API response) or a list of article IDs to search for. To specify multiple IDs, use a comma-separated string.

            **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.

        links : typing.Optional[str]
            The article link or list of article links to search for. To specify multiple links, use a comma-separated string.

            **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.

        from_ : typing.Optional[From]

        to : typing.Optional[To]

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        robots_compliant : typing.Optional[RobotsCompliant]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponseDto
            A successful response containing articles that match the provided links or IDs.

        Examples
        --------
        import datetime

        from newscatcher import NewscatcherApi

        client = NewscatcherApi(
            api_key="YOUR_API_KEY",
        )
        client.search_by_link.search_by_link_get(
            ids="5f8d0d55b6e45e00179c6e7e",
            links="https://nytimes.com/article1,https://bbc.com/article2",
            from_=datetime.datetime.fromisoformat(
                "2024-07-01 00:00:00+00:00",
            ),
            to=datetime.datetime.fromisoformat(
                "2024-01-01 00:00:00+00:00",
            ),
            page=2,
            page_size=50,
            robots_compliant=True,
        )
        """
        _response = self._raw_client.search_by_link_get(
            ids=ids,
            links=links,
            from_=from_,
            to=to,
            page=page,
            page_size=page_size,
            robots_compliant=robots_compliant,
            request_options=request_options,
        )
        return _response.data

    def search_by_link_post(
        self,
        *,
        ids: typing.Optional[Ids] = OMIT,
        links: typing.Optional[Links] = OMIT,
        from_: typing.Optional[From] = OMIT,
        to: typing.Optional[To] = OMIT,
        page: typing.Optional[Page] = OMIT,
        page_size: typing.Optional[PageSize] = OMIT,
        robots_compliant: typing.Optional[RobotsCompliant] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponseDto:
        """
        Searches for articles using their ID(s) or link(s).

        Parameters
        ----------
        ids : typing.Optional[Ids]

        links : typing.Optional[Links]

        from_ : typing.Optional[From]
            The starting point in time to search from. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.

            Formats with examples:
            - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
            - YYYY-MM-dd: `2024-07-01`
            - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
            - YYYY/mm/dd: `2024/07/01`
            - English phrases: `1 day ago`, `today`

        to : typing.Optional[To]
            The ending point in time to search up to. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.

            Formats with examples:
            - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
            - YYYY-MM-dd: `2024-07-01`
            - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
            - YYYY/mm/dd: `2024/07/01`
            - English phrases: `1 day ago`, `now`

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        robots_compliant : typing.Optional[RobotsCompliant]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponseDto
            A successful response containing articles that match the provided links or IDs.

        Examples
        --------
        from newscatcher import NewscatcherApi

        client = NewscatcherApi(
            api_key="YOUR_API_KEY",
        )
        client.search_by_link.search_by_link_post(
            links="https://www.reuters.com/business/energy/oil-prices-up-after-israeli-attacks-oversupply-caps-gains-2025-09-10/",
        )
        """
        _response = self._raw_client.search_by_link_post(
            ids=ids,
            links=links,
            from_=from_,
            to=to,
            page=page,
            page_size=page_size,
            robots_compliant=robots_compliant,
            request_options=request_options,
        )
        return _response.data


class AsyncSearchByLinkClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchByLinkClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchByLinkClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchByLinkClient
        """
        return self._raw_client

    async def search_by_link_get(
        self,
        *,
        ids: typing.Optional[str] = None,
        links: typing.Optional[str] = None,
        from_: typing.Optional[From] = None,
        to: typing.Optional[To] = None,
        page: typing.Optional[Page] = None,
        page_size: typing.Optional[PageSize] = None,
        robots_compliant: typing.Optional[RobotsCompliant] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponseDto:
        """
        Searches for articles based on specified links or IDs. You can filter results by date range.

        Parameters
        ----------
        ids : typing.Optional[str]
            The Newscatcher article ID (corresponds to the `_id` field in API response) or a list of article IDs to search for. To specify multiple IDs, use a comma-separated string.

            **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.

        links : typing.Optional[str]
            The article link or list of article links to search for. To specify multiple links, use a comma-separated string.

            **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.

        from_ : typing.Optional[From]

        to : typing.Optional[To]

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        robots_compliant : typing.Optional[RobotsCompliant]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponseDto
            A successful response containing articles that match the provided links or IDs.

        Examples
        --------
        import asyncio
        import datetime

        from newscatcher import AsyncNewscatcherApi

        client = AsyncNewscatcherApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.search_by_link.search_by_link_get(
                ids="5f8d0d55b6e45e00179c6e7e",
                links="https://nytimes.com/article1,https://bbc.com/article2",
                from_=datetime.datetime.fromisoformat(
                    "2024-07-01 00:00:00+00:00",
                ),
                to=datetime.datetime.fromisoformat(
                    "2024-01-01 00:00:00+00:00",
                ),
                page=2,
                page_size=50,
                robots_compliant=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_by_link_get(
            ids=ids,
            links=links,
            from_=from_,
            to=to,
            page=page,
            page_size=page_size,
            robots_compliant=robots_compliant,
            request_options=request_options,
        )
        return _response.data

    async def search_by_link_post(
        self,
        *,
        ids: typing.Optional[Ids] = OMIT,
        links: typing.Optional[Links] = OMIT,
        from_: typing.Optional[From] = OMIT,
        to: typing.Optional[To] = OMIT,
        page: typing.Optional[Page] = OMIT,
        page_size: typing.Optional[PageSize] = OMIT,
        robots_compliant: typing.Optional[RobotsCompliant] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponseDto:
        """
        Searches for articles using their ID(s) or link(s).

        Parameters
        ----------
        ids : typing.Optional[Ids]

        links : typing.Optional[Links]

        from_ : typing.Optional[From]
            The starting point in time to search from. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.

            Formats with examples:
            - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
            - YYYY-MM-dd: `2024-07-01`
            - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
            - YYYY/mm/dd: `2024/07/01`
            - English phrases: `1 day ago`, `today`

        to : typing.Optional[To]
            The ending point in time to search up to. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.

            Formats with examples:
            - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
            - YYYY-MM-dd: `2024-07-01`
            - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
            - YYYY/mm/dd: `2024/07/01`
            - English phrases: `1 day ago`, `now`

        page : typing.Optional[Page]

        page_size : typing.Optional[PageSize]

        robots_compliant : typing.Optional[RobotsCompliant]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponseDto
            A successful response containing articles that match the provided links or IDs.

        Examples
        --------
        import asyncio

        from newscatcher import AsyncNewscatcherApi

        client = AsyncNewscatcherApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.search_by_link.search_by_link_post(
                links="https://www.reuters.com/business/energy/oil-prices-up-after-israeli-attacks-oversupply-caps-gains-2025-09-10/",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_by_link_post(
            ids=ids,
            links=links,
            from_=from_,
            to=to,
            page=page,
            page_size=page_size,
            robots_compliant=robots_compliant,
            request_options=request_options,
        )
        return _response.data
